#ifndef CONFIG_H
#define CONFIG_H

#define VIOS_KERNEL_LOCATION 0x100000
#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define KERNEL_LONG_MODE_CODE_SELECTOR 0x18
#define KERNEL_LONG_MODE_TSS_SELECTOR 0x38

#define KERNEL_LONG_MODE_CODE_GDT_INDEX  3
#define KERNEL_LONG_MODE_DATA_GDT_INDEX 4
#define KERNEL_LONG_MODE_TSS_GDT_INDEX 7

#define TSS_DESCRIPTOR_TYPE 0x89  // 0x9 = 64-bit, bit 7 present
#define VIOS_TOTAL_INTERRUPTS 512

// 16 Bit number defining the total number of loaded
// entries.
#define VIOS_MEMORY_MAP_TOTAL_ENTRIES_LOCATION 0x210000

// Where to find the E820 records
#define VIOS_MEMORY_MAP_LOCATION 0x210008


// 100MB heap size
#define VIOS_HEAP_MINIMUM_SIZE_BYTES 104857600
#define VIOS_HEAP_BLOCK_SIZE 4096

// The minimal address the heap can point at, ensuring
// that the kernel does not get overwritten
#define VIOS_MINIMAL_HEAP_ADDRESS 0x01100000

// This is a minimal heap table starting address
#define VIOS_MINIMAL_HEAP_TABLE_ADDRESS 0x01000000

#define VIOS_MINIMAL_HEAP_TABLE_SIZE VIOS_MINIMAL_HEAP_ADDRESS-VIOS_MINIMAL_HEAP_TABLE_ADDRESS


#define VIOS_SECTOR_SIZE 512

#define VIOS_MAX_FILESYSTEMS 12
#define VIOS_MAX_FILE_DESCRIPTORS 512

#define VIOS_MAX_PATH 108

#define VIOS_TOTAL_GDT_SEGMENTS 6

#define VIOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define VIOS_USER_PROGRAM_STACK_SIZE 1024 * 16
#define VIOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define VIOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END VIOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - VIOS_USER_PROGRAM_STACK_SIZE

#define VIOS_MAX_PROGRAM_ALLOCATIONS 1024
#define VIOS_MAX_PROCESSES 12

#define USER_DATA_SEGMENT 0x33 // Also includes requested privilage level 3 
#define USER_CODE_SEGMENT 0x2B // Also includes RPL3

#define VIOS_MAX_ISR80H_COMMANDS 1024

#define VIOS_KEYBOARD_BUFFER_SIZE 1024

#endif
