#ifndef ISR80H_H
#define ISR80H_H

struct interrupt_frame;

enum SystemCommands
{
    SYSTEM_COMMAND0_EXIT,
    SYSTEM_COMMAND1_PRINT,
    SYSTEM_COMMAND2_GETKEY,
    SYSTEM_COMMAND3_PUTCHAR,
    SYSTEM_COMMAND4_MALLOC,
    SYSTEM_COMMAND5_FREE,
    SYSTEM_COMMAND6_PROCESS_LOAD_START,
    SYSTEM_COMMAND7_INVOKE_SYSTEM_COMMAND,
    SYSTEM_COMMAND8_GET_PROGRAM_ARGUMENTS,
    SYSTEM_COMMAND9_SLEEP,
    SYSTEM_COMMAND10_READ,
    SYSTEM_COMMAND11_VIX_DRAW_PIXEL,
    SYSTEM_COMMAND12_VIX_DRAW_RECT,
    SYSTEM_COMMAND13_VIX_FILL_RECT,
    SYSTEM_COMMAND14_VIX_CLEAR_SCREEN,
    SYSTEM_COMMAND15_VIX_PRESENT_FRAME,
    SYSTEM_COMMAND16_VIX_GET_SCREEN_INFO,
    SYSTEM_COMMAND17_VIX_DRAW_LINE,
    SYSTEM_COMMAND18_VIX_DRAW_CIRCLE,
    SYSTEM_COMMAND19_VIX_FILL_CIRCLE,
};

void isr80h_register_commands();
void *isr80h_command6_process_load_start(struct interrupt_frame *frame);

#endif