name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install required tools
      run: |
        sudo apt update
        sudo apt install -y nasm make curl

    - name: Download and install i686-elf toolchain
      run: |
        curl -L https://raw.githubusercontent.com/lordmilko/i686-elf-tools/refs/heads/master/i686-elf-tools.sh -o i686-elf-tools.sh
        chmod +x i686-elf-tools.sh
        ./i686-elf-tools.sh

    - name: Verify toolchain
      run: |
        i686-elf-gcc --version
        i686-elf-as --version

    - name: Build project
      run: make

    - name: Run distcheck
      run: make distcheck

    - name: Prepare output
      run: |
        mkdir -p bin
        cp os.bin bin/os.bin

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: os-bin
        path: bin/os.bin
